#!/usr/bin/env bash

tracer() {
  local max_line_length=$(($(tput cols) - 20))
 
  { PS4='\e[0D ${BASH_SOURCE}:${FUNCNAME:-<script>}:${LINENO}:\e[m '; set -x; "$@"; } 2>&1 >/dev/null | {
    # skip the first line
    IFS= read -r

    local start=${EPOCHREALTIME/,/}
    local last=$start

    IFS= read -r

    local last_line=$REPLY
    local elapsed_line

    while IFS= read -r; do
      elapsed_line=$((${EPOCHREALTIME/,/} - last))
      last=${EPOCHREALTIME/,/}

      printf '%4d.%04ds \e[7m \e[m %s\n' "$((elapsed_line / 1000000))" "$((elapsed_line % 1000000 / 100))" "${last_line}"

      last_line=$REPLY
    done

    local elapsed_total=$((last - start))
    printf '           \e[7m \e[m\n     Total \e[7m \e[m %d.%04d\n' "$((elapsed_total / 1000000))" "$((elapsed_total % 1000000 / 100))"
  }
}

__tracer_print_lines() {
  local line=$1
  local max_line_length=$2

  local raw=${last_line:0:$max_line_length}

  while ((${#raw} > max_line_length)); do
    printf '           \e[7m \e[m %s\n' "${line:0:$max_line_length}"

    line=${line:$max_line_length}
  done
}
